export const LOAD_MOVIES_SUCCESS = "LOAD_MOVIES_SUCCESS";
export const LOAD_TVSHOWS_SUCCESS = "LOAD_TVSHOWS_SUCCESS";
export const UPDATE_SEARCH_QUERY = "UPDATE_SEARCH_QUERY";
export const CHOOSE_CATEGORY = "CHOOSE_CATEGORY";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const LOAD_CASTING_SUCCESS = "LOAD_CASTING_SUCCESS";
export const LOAD_SLIDER_FROM_CASTING = "LOAD_SLIDER_FROM_CASTING";
export const ADD_FAVORITE_SUCCESS = "ADD_FAVORITE_SUCCESS";

export const SORT_LIST_BY_NAME = "SORT_LIST_BY_NAME";
export const REVERSE_LIST_BY_NAME = "REVERSE_LIST_BY_NAME";
export const SORT_LIST_BY_POPULARITY = "SORT_LIST_BY_POPULARITY";
export const REVERSE_LIST_BY_POPULARITY = "REVERSE_LIST_BY_POPULARITY";
export const SORT_LIST_BY_NOTATION = "SORT_LIST_BYNOTATION";
export const REVERSE_LIST_BY_NOTATION = "REVERSE_LIST_BY_NOTATION";
export const SORT_LIST_BY_DATE = "SORT_LIST_BY_DATE";
export const REVERSE_LIST_BY_DATE = "REVERSE_LIST_BY_DATE";
