export const LOAD_MOVIES_SUCCESS = "LOAD_MOVIES_SUCCESS";
export const LOAD_TVSHOWS_SUCCESS = "LOAD_TVSHOWS_SUCCESS";
export const UPDATE_SEARCH_QUERY = "UPDATE_SEARCH_QUERY";
export const CHOOSE_CATEGORY = "CHOOSE_CATEGORY";
